### ISSUE TITLE
BloodDonorRegistration.html

### ISSUE THREAD

**Issue by JITUaiub** [JITUaiub/MediPortal#1]
Use project given resource to create a blood donor registration form.

1. -Use some information regarding to Blood donation
2. -design using multiple section
3. -Add checkbox "I agreed and ready to donate blood."

**N.B. - Please intend your code properly.**

**Comment by rpmshuvo** [comment]
I think it's done.Eligibility test related question gula jokhon blood donate korte chaibe tokhon asked kora jaitepare.

**Comment by JITUaiub** [comment]
blood donor a kichu modification lagbe, ekta normal member e donate dite parbe, ekhane duita option thakbe, create a new account or continue with normal account. If normal account selected, just ask user for blood info.
- Add DOB to Doctor & normal member registration.
- Remove Don't Know from Blood donor reg. form, replace that with Select one
