### ISSUE TITLE
Add Report Module to Member Login

### ISSUE THREAD

**Issue by JITUaiub** [JITUaiub/MediPortal#3]
Design menu like below:
**Report**

- Appointment Status

- Prescriptions

- Appointment History

Now, also Design 3 pages according to class lab module.

**N.B. Please intend your code**
_**Leave a comment if have any query**_

**Comment by rpmshuvo** [comment]
"MemberLoggedIn.html" create kore ki add korbo

**Comment by JITUaiub** [comment]
Work on new assignment first

**Comment by JITUaiub** [comment]
Added !! !!!
