### ISSUE TITLE
Add Copyright info to all pages

### ISSUE THREAD

**Issue by JITUaiub** [JITUaiub/MediPortal#5]
use this format:
**&copy;2017 MediPortal. All rights reserved.**

Must align the text to center for better view

**Comment by tuhi009** [comment]
hint: use object to include a footer.
and clean the code. your teacher is going to have a heart attack

**Comment by JITUaiub** [comment]
Thanks for the suggession. But so far our teacher policy, we can't use them for now.

**Comment by islam-shamiul** [comment]
done.....
