### ISSUE TITLE
Design the following pages in Doctor Portal

### ISSUE THREAD

**Issue by JITUaiub** [JITUaiub/MediPortal#8]
Design following two pages, Use **brainstorming** for ideas, Implement as many feature you can Imagine.
**1.** prescriptions.html -> for Older Prescriptions pescribed by doctor
**2.** newprescriptions.html -> for Creating a new prescription.
**3.** patientHistory.html -> For showing past patient, also show their prescription record and basic profile.

Doctor can serve a patient with or without appointment.
Design new prescription like above describe

**N.B. Intend your code properly, and use proper naming in input types.**

**Comment by rpmshuvo** [comment]
Work Done !!!!
